#!/usr/bin/env bash
# Bash script displaying lines containing the 'bash' word, thus allowing you to easily get the PID of your bash process
# shellcheck disable=SC2009
# Requirement:
#	-You cannot use pgrep

ps -faux | grep "bash"
